import type { GuidePost } from '../types';

/** Top-Listen aus deiner Tabelle — neue Listen: Objekt hier anfügen. */
export const TOPLIST_POSTS: GuidePost[] = [
    {
        id: 'top-proteinquellen',
        format: 'toplist',
        title: 'Meine Top Proteinquellen',
        lead: 'Was bei mir wirklich oft auf dem Teller landet — schnell, sättigend, viel Protein.',
        headerImage: 'headers/top-proteinquellen.svg',
        items: [
            { name: 'Magerhackfleisch 70 %', type: 'Lebensmittel', category: 'Proteinquelle', why: 'Sehr viel Protein, sättigt stark, vielseitig.', used: true },
            { name: 'Skyr', type: 'Lebensmittel', category: 'Proteinquelle', why: 'Viel Protein, wenig Fett, gut als Snack oder Frühstück.', used: true },
            { name: 'Fisch', type: 'Lebensmittel', category: 'Proteinquelle', why: 'Viel Protein bei wenig Kalorien, TK geht schnell.', used: true },
            { name: 'Pute', type: 'Lebensmittel', category: 'Proteinquelle', why: 'Mager, viel Protein — Aufschnitt oder Braten.', used: true },
            { name: 'Hähnchen', type: 'Lebensmittel', category: 'Proteinquelle', why: 'Klassiker: günstig, mager, überall einsetzbar.', used: true },
            { name: 'Proteinshake', type: 'Lebensmittel', category: 'Proteinquelle', why: 'Praktisch, wenn Essen nicht reicht oder unterwegs.', used: true },
        ],
    },
    {
        id: 'top-tiefkuehl',
        format: 'toplist',
        title: 'Meine Top Tiefkühlprodukte',
        lead: 'Wenig Aufwand, trotzdem sinnvoll — für stressige Tage.',
        headerImage: 'headers/top-tiefkuehl.svg',
        items: [
            { name: 'Chicken Nuggets', type: 'Lebensmittel', category: 'Tiefkühl', why: 'Schnell, proteinreich — auf Qualität achten.', used: true },
            { name: 'Gyros', type: 'Lebensmittel', category: 'Tiefkühl', why: 'Wenig Aufwand, schmeckt — Portion im Blick behalten.', used: true },
            { name: 'TK-Fischfilet', type: 'Lebensmittel', category: 'Tiefkühl', why: 'Schnell, mager, viel Protein.', used: true },
            { name: 'Süßkartoffelpommes', type: 'Lebensmittel', category: 'Tiefkühl', why: 'Ofen, fertig — als Beilage ohne großen Stress.', used: true },
        ],
    },
    {
        id: 'top-unverzichtbar',
        format: 'toplist',
        title: 'Unverzichtbar im Alltag',
        lead: 'Dinge, die mir Kalorien sparen oder Heißhunger abfangen.',
        headerImage: 'headers/top-unverzichtbar.svg',
        items: [
            { name: 'Heinz Zero Ketchup', type: 'Lebensmittel', category: 'Unverzichtbar', why: 'Geschmack ohne die Kalorien von normalem Ketchup.', used: true },
            { name: 'Zero-Getränke', type: 'Lebensmittel', category: 'Unverzichtbar', why: 'Süßer Geschmack, kaum Kalorien — für mich Standard.', used: true },
            { name: 'Proteinriegel', type: 'Lebensmittel', category: 'Unverzichtbar', why: 'Hilft gegen Heißhunger, liefert Protein unterwegs.', used: true },
        ],
    },
    {
        id: 'top-snacks',
        format: 'toplist',
        title: 'Meine Top Snacks',
        lead: 'Viel Volumen oder Protein — nicht nur „leer“ knabbern.',
        headerImage: 'headers/top-snacks.svg',
        items: [
            { name: 'Popcorn', type: 'Lebensmittel', category: 'Snack', why: 'Viel Volumen, wenig Kalorien — ohne Butter-Exzess.', used: true },
            { name: 'Maiswaffeln', type: 'Lebensmittel', category: 'Snack', why: 'Knusprig, wenig kcal, gut mit Dip.', used: true },
            { name: 'Wassereis', type: 'Lebensmittel', category: 'Snack', why: 'Süß ohne viele Kalorien — besonders im Sommer.', used: true },
            { name: 'Protein-Cheesecake (selbst)', type: 'Lebensmittel', category: 'Snack', why: 'Proteinreich, fühlt sich an wie Cheat — Rezept folgt.', used: true },
        ],
    },
    {
        id: 'top-getraenke',
        format: 'toplist',
        title: 'Meine Top Getränke',
        lead: 'Geschmack und Wachheit — ohne den Kalorienplan zu sprengen.',
        headerImage: 'headers/top-getraenke.svg',
        items: [
            { name: 'Cola Zero', type: 'Lebensmittel', category: 'Getränk', why: 'Klassiker ohne Zucker.', used: true },
            { name: 'Wasser mit Sirup', type: 'Lebensmittel', category: 'Getränk', why: 'Mehr Geschmack als plain — Sirup kalorienarm wählen.', used: true },
            { name: 'Kaffee mit Mandelmilch', type: 'Lebensmittel', category: 'Getränk', why: 'Wenig kcal, morgens fest dabei.', used: true },
            { name: 'Energydrink', type: 'Lebensmittel', category: 'Getränk', why: 'Wachheit — bewusst einplanen, nicht literweise.', used: true },
        ],
    },
    {
        id: 'top-saucen',
        format: 'toplist',
        title: 'Meine Top Saucen',
        lead: 'Essen schmeckt besser — ohne jedes Mal hunderte Kalorien drauf.',
        headerImage: 'headers/top-saucen.svg',
        items: [
            { name: 'Miracle Whip Balance', type: 'Lebensmittel', category: 'Sauce', why: 'Cremig, deutlich weniger Kalorien als Mayo.', used: true },
            { name: 'Kalorienarme Saucen (verschiedene)', type: 'Lebensmittel', category: 'Sauce', why: 'Curry, Knoblauch, BBQ light — Abwechslung.', used: true },
            { name: 'Senf', type: 'Lebensmittel', category: 'Sauce', why: 'Fast keine Kalorien, viel Geschmack.', used: true },
        ],
    },
    {
        id: 'top-supplements',
        format: 'toplist',
        title: 'Meine Top Supplements',
        lead: 'Ergänzung — ersetzt keine gute Ernährung, kann aber Lücken schließen.',
        headerImage: 'headers/top-supplements.svg',
        items: [
            { name: 'Vitamin D3 + K2', type: 'Supplement', category: 'Basis', why: 'Sinnvoll, wenn wenig Sonne — Blutwert mit Arzt klären.', used: true },
            { name: 'Omega-3', type: 'Supplement', category: 'Basis', why: 'Ergänzt fetten Fisch, wenn der selten auf dem Plan ist.', used: true },
            { name: 'Magnesium', type: 'Supplement', category: 'Basis', why: 'Alltag, Schlaf, Training — individuell unterschiedlich.', used: true },
            { name: 'Kreatin', type: 'Supplement', category: 'Training', why: 'Evidenz für Kraft — 3–5 g täglich, günstig.', used: true },
        ],
    },
    {
        id: 'top-marken',
        format: 'toplist',
        title: 'Meine Top Marken',
        lead: 'Wo ich oft bestelle — Preis, Sortiment, Geschmack.',
        headerImage: 'headers/top-marken.svg',
        items: [
            { name: 'HSN', type: 'Marke', category: 'Alternative', why: 'Große Auswahl, oft Aktionen.', used: true },
            { name: 'Bodylab24', type: 'Marke', category: 'Alternative', why: 'Deutscher Shop, solide Basics.', used: true },
            { name: 'MyProtein / Maxi Nutrition', type: 'Marke', category: 'Alternative', why: 'Bekannt, viel Protein-Sortiment.', used: true },
        ],
    },
    {
        id: 'top-apps-tools',
        format: 'toplist',
        title: 'Meine Top Apps & Tools',
        lead: 'Was mir beim Tracken und Dranbleiben hilft.',
        headerImage: 'headers/top-apps.svg',
        items: [
            { name: 'FDDB', type: 'Software', category: 'Apps', why: 'Große deutsche Lebensmitteldatenbank.', used: true },
            { name: 'Yazio', type: 'Software', category: 'Apps', why: 'Übersichtlich, viele nutzen es.', used: true },
            { name: 'MyFitnessPal', type: 'Software', category: 'Apps', why: 'International, riesige DB.', used: true },
            { name: 'DailyTogether', type: 'Software', category: 'Tools', why: 'Gemeinsam planen — Paar, Familie, Haushalt.', used: true },
            { name: 'eno.rocks', type: 'Software', category: 'Tools', why: 'Meine Rechner und Begriffe — ohne Abo.', used: true },
        ],
    },
    {
        id: 'top-hardware',
        format: 'toplist',
        title: 'Meine Top Hardware',
        lead: 'Küche und Training — was sich für mich gelohnt hat.',
        headerImage: 'headers/top-hardware.svg',
        items: [
            { name: 'Renpho-Waage', type: 'Hardware', category: 'Tracking', why: 'Trendgewicht, KFA-Schätzung — nicht täglich stressen.', used: true },
            { name: 'Kurzhanteln', type: 'Hardware', category: 'Training', why: 'Zuhause trainieren, flexibel steigerbar.', used: true },
            { name: 'Hantelbank', type: 'Hardware', category: 'Training', why: 'Mehr Übungsoptionen als nur Boden.', used: true },
            { name: 'Smartwatch', type: 'Hardware', category: 'Tracking', why: 'Schritte, NEAT im Blick.', used: true },
            { name: 'Küchenwaage', type: 'Hardware', category: 'Küche', why: 'Tracken ohne Raten — Öl, Nüsse, Reis.', used: true },
            { name: 'Protein-Shaker', type: 'Hardware', category: 'Küche', why: 'Klumpenfrei, unterwegs.', used: true },
            { name: 'Heißluftfritteuse', type: 'Hardware', category: 'Küche', why: 'Knusprig mit weniger Öl.', used: true },
        ],
    },
    {
        id: 'top-organisation',
        format: 'toplist',
        title: 'Meine Top Organisation',
        lead: 'Weniger Chaos in Küche und Vorrat.',
        headerImage: 'headers/top-organisation.svg',
        items: [
            { name: 'Etikettierer', type: 'Organisation', category: 'Küche', why: 'Vorkochen, einfrieren, wiederfinden.', used: true },
            { name: 'Aufbewahrungsboxen', type: 'Organisation', category: 'Küche', why: 'Meal Prep ohne Durcheinander.', used: true },
            { name: 'Extra Messbecher', type: 'Organisation', category: 'Küche', why: 'Reis, Haferflocken — immer gleiche Portion.', used: true },
        ],
    },
    {
        id: 'top-gewohnheiten',
        format: 'toplist',
        title: 'Meine Top Gewohnheiten',
        lead: 'Nicht Tools — Verhalten, das langfristig trägt.',
        headerImage: 'headers/top-gewohnheiten.svg',
        items: [
            { name: 'Kalorien zählen', type: 'Gewohnheit', category: 'Tracking', why: 'Bewusstsein schaffen — muss nicht für immer sein.', used: true },
            { name: 'Protein hoch halten', type: 'Gewohnheit', category: 'Ernährung', why: 'Sättigung, Muskelerhalt beim Defizit.', used: true },
            { name: 'Täglich wiegen', type: 'Gewohnheit', category: 'Tracking', why: 'Trend über Wochen, nicht Panik am Einzeltag.', used: true },
            { name: 'Geduld', type: 'Gewohnheit', category: 'Mindset', why: 'Fortschritt ist nicht linear.', used: true },
            { name: 'Intermittierendes Fasten', type: 'Gewohnheit', category: 'Ernährung', why: 'Kann helfen — ist aber kein Muss für jeden.', used: true },
        ],
    },
];
