import type { GuidePost } from '../types';

export const TOPLIST_POSTS: GuidePost[] = [
    {
        id: 'top-proteinquellen',
        format: 'toplist',
        title: 'Meine Top Proteinquellen',
        lead: 'Protein ist beim Abnehmen und Muskelaufbau der wichtigste Makronährstoff, weil es sättigt und Muskelmasse schützt. Diese Lebensmittel landen bei mir am häufigsten auf dem Teller, weil sie viel Protein pro Kalorie liefern und sich gut in den Alltag integrieren lassen.',
        headerImage: 'headers/top-proteinquellen.svg',
        items: [
            {
                name: 'Magerhackfleisch 70 %',
                type: 'Lebensmittel',
                category: 'Proteinquelle',
                text: 'Magerhack liefert pro 100 Gramm etwa 20 bis 22 Gramm Protein bei vergleichsweise wenig Fett. Das macht es ideal im Kaloriendefizit, weil du bei weniger Energie trotzdem gut versorgt bleibst. Es lässt sich vielseitig zubereiten, portionieren und für mehrere Tage vorkochen.',
            },
            {
                name: 'Skyr',
                type: 'Lebensmittel',
                category: 'Proteinquelle',
                text: 'Skyr ist fermentierter Magerquark mit sehr hohem Proteingehalt und wenig Fett. Er eignet sich morgens, als Snack oder als Basis für süße Gerichte ohne viele Kalorien. Die Sättigung hält oft länger als bei klassischem Joghurt mit mehr Zucker.',
            },
            {
                name: 'Fisch',
                type: 'Lebensmittel',
                category: 'Proteinquelle',
                text: 'Fisch kombiniert viel Protein mit wenig Kalorien und liefert zusätzlich Omega 3 Fettsäuren, die der Körper nicht selbst bilden kann. Besonders magere Sorten wie Kabeljau oder Seelachs passen gut in eine diätfreundliche Ernährung. Tiefkühlfilets sparen Zeit und sind oft günstiger als frischer Fisch.',
            },
            {
                name: 'Pute',
                type: 'Lebensmittel',
                category: 'Proteinquelle',
                text: 'Putenfleisch ist sehr mager und liefert pro Portion viel Protein bei wenig Fett. Aufschnitt, Braten oder Streifen aus der Pfanne lassen sich schnell in Salate, Wraps oder Meal Prep einbauen. Für mich ist Pute eine einfache Variante, wenn Hähnchen mal langweilig wird.',
            },
            {
                name: 'Hähnchen',
                type: 'Lebensmittel',
                category: 'Proteinquelle',
                text: 'Hähnchenbrust ist eine der günstigsten und zugänglichsten Proteinquellen überhaupt. Sie lässt sich in fast jede Küche integrieren und nimmt Gewürze und Marinaden gut an. Beim Abnehmen hilft die hohe Proteinmenge vor allem dabei, Hunger zwischen den Mahlzeiten zu reduzieren.',
            },
            {
                name: 'Proteinshake',
                type: 'Lebensmittel',
                category: 'Proteinquelle',
                text: 'Ein Shake ersetzt keine vollwertige Mahlzeit, schließt aber Lücken, wenn unterwegs oder zu wenig Zeit zum Kochen ist. Molkenprotein wird schnell verdaut und eignet sich gut nach dem Training oder als Ergänzung am Abend. Entscheidend ist, dass der Rest des Tages weiterhin aus echten Lebensmitteln besteht.',
            },
        ],
    },
    {
        id: 'top-tiefkuehl',
        format: 'toplist',
        title: 'Meine Top Tiefkühlprodukte',
        lead: 'Tiefkühl bedeutet nicht automatisch ungesund. Gefrorene Produkte sind oft schockgefrostet und behalten Nährstoffe gut. Für stressige Tage sind sie bei mir die erste Wahl, wenn es schnell gehen muss und trotzdem Protein auf dem Plan stehen soll.',
        headerImage: 'headers/top-tiefkuehl.svg',
        items: [
            {
                name: 'Chicken Nuggets',
                type: 'Lebensmittel',
                category: 'Tiefkühl',
                text: 'Gute Nuggets aus Hähnchenfleisch liefern Protein und sind in wenigen Minuten fertig. Der Unterschied liegt in der Zutatenliste und den Nährwerten pro 100 Gramm. Im Ofen statt in der Fritteuse sparst du zusätzlich Fett und Kalorien.',
            },
            {
                name: 'Gyros',
                type: 'Lebensmittel',
                category: 'Tiefkühl',
                text: 'Fertiges Gyros aus dem Tiefkühlregal spart Zeit und schmeckt, wenn du es mit Salat und Joghurt kombinierst. Achte auf den Fettgehalt und rechne die Portion in dein Tagesbudget ein. So bleibt es ein praktisches Gericht statt eines ungeplanten Kalorienausreißers.',
            },
            {
                name: 'TK Fischfilet',
                type: 'Lebensmittel',
                category: 'Tiefkühl',
                text: 'Gefrorenes Fischfilet ist in der Regel schon geschält und portioniert. In der Pfanne oder im Ofen ist es in unter 20 Minuten fertig und liefert viel Protein bei wenig Kohlenhydraten. Für mich ist das die einfachste Art, öfter Fisch zu essen, ohne jeden Tag frisch einkaufen zu müssen.',
            },
            {
                name: 'Süßkartoffelpommes',
                type: 'Lebensmittel',
                category: 'Tiefkühl',
                text: 'Süßkartoffeln liefern Kohlenhydrate, Ballaststoffe und Mikronährstoffe wie Beta Carotin. Als Pommes aus dem Ofen sind sie eine unkomplizierte Beilage zu Fleisch oder Fisch. Die Kalorien zählen trotzdem, deshalb lohnt sich eine klare Portion auf der Waage.',
            },
        ],
    },
    {
        id: 'top-unverzichtbar',
        format: 'toplist',
        title: 'Unverzichtbar im Alltag',
        lead: 'Diese Dinge helfen mir, den Ernährungsplan durchzuhalten, ohne mich ständig eingeschränkt zu fühlen. Es geht weniger um Perfektion als um kleine Erleichterungen, die über Wochen den Unterschied machen.',
        headerImage: 'headers/top-unverzichtbar.svg',
        items: [
            {
                name: 'Heinz Zero Ketchup',
                type: 'Lebensmittel',
                category: 'Unverzichtbar',
                text: 'Klassisches Ketchup bringt überraschend viele Kalorien durch Zucker mit. Die Zero Variante liefert den gewohnten Geschmack bei einem Bruchteil der Energie. Für Pommes, Wraps oder als Dip macht das den Unterschied, wenn du sonst sauber trackst.',
            },
            {
                name: 'Zero Getränke',
                type: 'Lebensmittel',
                category: 'Unverzichtbar',
                text: 'Kalorienfreie Limonaden und Cola Varianten helfen, wenn du süßen Geschmack willst, aber dein Budget eng ist. Sie füllen den Magen nicht sinnvoll, ersetzen aber zuckerhaltige Getränke, die schnell 200 bis 300 Kalorien pro Flasche ausmachen können. Für mich sind sie ein Werkzeug, kein Pflichtprogramm.',
            },
            {
                name: 'Proteinriegel',
                type: 'Lebensmittel',
                category: 'Unverzichtbar',
                text: 'Ein guter Proteinriegel liefert 15 bis 20 Gramm Protein und passt in die Tasche. Er hilft gegen Heißhunger, wenn zwischen zwei Mahlzeiten zu viel Zeit liegt. Wichtig ist, Nährwerte zu vergleichen, weil manche Riegel kaum Protein und viel Zucker enthalten.',
            },
        ],
    },
    {
        id: 'top-snacks',
        format: 'toplist',
        title: 'Meine Top Snacks',
        lead: 'Snacks müssen nicht tabu sein. Sinnvolle Optionen liefern Volumen oder Protein, damit du satt wirst, ohne den Tagesplan zu sprengen. Diese Auswahl nutze ich, wenn der Abend lang wird oder der Hunger unerwartet kommt.',
        headerImage: 'headers/top-snacks.svg',
        items: [
            {
                name: 'Popcorn',
                type: 'Lebensmittel',
                category: 'Snack',
                text: 'Luftiges Popcorn hat pro Portion wenig Kalorien, aber viel Volumen. Das hilft psychologisch, wenn du abends etwas Knabberbares willst. Ohne Butter und mit wenig Salz bleibt es eine leichte Option statt einer Kalorienbombe aus dem Kino.',
            },
            {
                name: 'Maiswaffeln',
                type: 'Lebensmittel',
                category: 'Snack',
                text: 'Maiswaffeln sind knusprig, fettarm und schnell portioniert. Mit Frischkäse, Hummus oder Putenaufschnitt werden sie zu einem kleinen proteinreichen Snack. Allein gegessen sättigen sie weniger, kombiniert aber gut.',
            },
            {
                name: 'Wassereis',
                type: 'Lebensmittel',
                category: 'Snack',
                text: 'Wassereis enthält meist nur Wasser, Süßstoff und Aromen und damit sehr wenig Kalorien. Im Sommer ist es für mich die einfachste Antwort auf Gelüste nach Süßem. Es ersetzt keine Mahlzeit, beruhigt aber den Appetit auf Eis und Zucker.',
            },
            {
                name: 'Protein Cheesecake selbstgemacht',
                type: 'Lebensmittel',
                category: 'Snack',
                text: 'Ein Cheesecake auf Skyr oder Magerquark Basis liefert viel Protein und fühlt sich an wie Naschen. Die Kalorien lassen sich besser steuern als bei fertigem Kuchen aus dem Laden. Genau deshalb steht er in meiner Snack Liste und nicht nur als Rezeptidee.',
            },
        ],
    },
    {
        id: 'top-getraenke',
        format: 'toplist',
        title: 'Meine Top Getränke',
        lead: 'Flüssige Kalorien werden leicht unterschätzt. Diese Getränke passen zu meinem Alltag, weil sie entweder kaum Energie liefern oder einen klaren Nutzen für Wachheit und Routine haben.',
        headerImage: 'headers/top-getraenke.svg',
        items: [
            {
                name: 'Cola Zero',
                type: 'Lebensmittel',
                category: 'Getränk',
                text: 'Cola Zero schmeckt für viele nah an der Vollzucker Variante, liefert aber keine Kalorien. Als Ersatz für normale Cola sparst du pro Glas etwa 140 Kilokalorien. Für die Zähne und den Appetit gilt trotzdem: nicht literweise, aber bewusst einplanen.',
            },
            {
                name: 'Wasser mit Sirup',
                type: 'Lebensmittel',
                category: 'Getränk',
                text: 'Sirup mit wenig oder keinem Zucker macht plain Wasser trinkbarer. So trinkst du insgesamt mehr Flüssigkeit, ohne Limonade aus dem Automaten zu kaufen. Die Kalorien hängen stark von der Dosierung ab, deshalb lohnt sich Messen am Anfang.',
            },
            {
                name: 'Kaffee mit Mandelmilch',
                type: 'Lebensmittel',
                category: 'Getränk',
                text: 'Schwarzer Kaffee hat fast keine Kalorien und kann die Wachheit unterstützen. Mandelmilch ungesüßt bringt etwas Geschmack und Cremigkeit bei wenigen Kilokalorien pro Portion. Für mich ist das der Standard morgens statt milchhaltiger Varianten aus dem Café.',
            },
            {
                name: 'Energydrink',
                type: 'Lebensmittel',
                category: 'Getränk',
                text: 'Energydrinks liefern Koffein, das kurzfristig Wachheit und Konzentration verbessern kann. Viele Varianten sind kalorienfrei oder fast kalorienfrei. Zu spät am Tag können sie den Schlaf stören, deshalb plane ich sie eher vormittags und nicht als Dauerlösung.',
            },
        ],
    },
    {
        id: 'top-saucen',
        format: 'toplist',
        title: 'Meine Top Saucen',
        lead: 'Saucen machen trockene Diätgerichte essbar. Die Kalorien aus Öl und Mayo summieren sich aber schnell. Diese Optionen geben Geschmack, ohne jede Mahlzeit unnötig aufzublähen.',
        headerImage: 'headers/top-saucen.svg',
        items: [
            {
                name: 'Miracle Whip Balance',
                type: 'Lebensmittel',
                category: 'Sauce',
                text: 'Miracle Whip Balance hat deutlich weniger Fett und Kalorien als klassische Mayonnaise. Für Salate, Dips oder Sandwiches reicht oft eine kleine Menge. Der Geschmack ist cremig genug, dass du nicht auf die volle Kalorienvariante angewiesen bist.',
            },
            {
                name: 'Kalorienarme Saucen',
                type: 'Lebensmittel',
                category: 'Sauce',
                text: 'Viele Hersteller bieten Curry, Knoblauch oder BBQ Saucen mit reduziertem Zucker und Fett an. Sie helfen, Abwechslung in den Alltag zu bringen, wenn Hähnchen und Reis sonst eintönig wirken. Nährwerte pro 100 Gramm vergleichen lohnt sich, weil die Spanne groß ist.',
            },
            {
                name: 'Senf',
                type: 'Lebensmittel',
                category: 'Sauce',
                text: 'Senf enthält praktisch keine Kalorien und viel Geschmack. Er passt zu Fleisch, Wurst oder als Basis für selbst gemachte Dressings. Für mich ist Senf die einfachste Würze, wenn es schnell gehen soll und das Kalorienbudget knapp ist.',
            },
        ],
    },
    {
        id: 'top-supplements',
        format: 'toplist',
        title: 'Meine Top Supplements',
        lead: 'Supplements ergänzen die Ernährung, ersetzen sie aber nicht. Diese Auswahl basiert auf evidenznahen Grundlagen und persönlicher Erfahrung im Alltag und Training.',
        headerImage: 'headers/top-supplements.svg',
        items: [
            {
                name: 'Vitamin D3 mit K2',
                type: 'Supplement',
                category: 'Basis',
                text: 'Vitamin D entsteht vor allem durch Sonnenlicht auf der Haut. In Deutschland haben viele Menschen im Winter einen zu niedrigen Spiegel, was Stimmung, Immunsystem und Knochenstoffwechsel beeinflussen kann. K2 wird oft kombiniert, weil es bei der Verwertung von Calcium eine Rolle spielt. Ein Bluttest beim Arzt zeigt, ob Supplementierung sinnvoll ist.',
            },
            {
                name: 'Omega 3',
                type: 'Supplement',
                category: 'Basis',
                text: 'Omega 3 Fettsäuren unterstützen Herz, Gehirn und Entzündungsregulation. Wer selten fetten Fisch isst, deckt den Bedarf über Fischöl oder Algenöl ab. Die Qualität hängt von Reinheit und EPA sowie DHA Gehalt ab.',
            },
            {
                name: 'Magnesium',
                type: 'Supplement',
                category: 'Basis',
                text: 'Magnesium ist an über 300 enzymatischen Reaktionen beteiligt, unter anderem Muskelkontraktion und Nervensystem. Sport, Schwitzen und Stress erhöhen den Bedarf manchmal. Formen wie Citrat oder Bisglycinat werden oft besser vertragen als reines Oxid.',
            },
            {
                name: 'Kreatin',
                type: 'Supplement',
                category: 'Training',
                text: 'Kreatinmonohydrat ist eine der am besten erforschten Ergänzungen für Kraft und Leistung im Wiederholungsbereich. Es hilft, mehr Energie in kurzen maximalen Belastungen bereitzustellen. Üblicherweise reichen 3 bis 5 Gramm täglich, auch an trainingsfreien Tagen.',
            },
        ],
    },
    {
        id: 'top-marken',
        format: 'toplist',
        title: 'Meine Top Marken',
        lead: 'Wo du kaufst, beeinflusst Preis, Geschmack und Verfügbarkeit. Diese Shops nutze ich für Proteinpulver, Snacks und Basics, wenn Aktionen oder Sortiment passen.',
        headerImage: 'headers/top-marken.svg',
        items: [
            {
                name: 'HSN',
                type: 'Marke',
                category: 'Shop',
                text: 'HSN hat ein sehr breites Sortiment an Protein, Snacks und Supplements. Regelmäßige Rabatte machen größere Bestellungen interessant. Für mich ist es ein guter Ort, um Preise zu vergleichen, bevor ich woanders kaufe.',
            },
            {
                name: 'Bodylab24',
                type: 'Marke',
                category: 'Shop',
                text: 'Bodylab24 ist ein deutscher Anbieter mit schnellem Versand innerhalb Deutschlands. Die Eigenmarken sind oft preiswert und für den Alltag völlig ausreichend. Besonders Proteinpulver und Riegel bestelle ich hier gelegentlich.',
            },
            {
                name: 'MyProtein',
                type: 'Marke',
                category: 'Shop',
                text: 'MyProtein ist international bekannt und hat häufig starke Rabattaktionen. Das Sortiment an Geschmacksrichtungen ist groß, was beim täglichen Shake hilft. Lieferzeiten und Versandkosten solltest du vor der Bestellung prüfen.',
            },
        ],
    },
    {
        id: 'top-apps-tools',
        format: 'toplist',
        title: 'Meine Top Apps und Tools',
        lead: 'Tracking und Struktur machen den Unterschied, wenn du aus Bauchgefühl in einen planbaren Alltag wechseln willst. Diese Apps und Tools nutze ich selbst oder habe sie mitentwickelt.',
        headerImage: 'headers/top-apps.svg',
        items: [
            {
                name: 'FDDB',
                type: 'Software',
                category: 'Apps',
                text: 'Die Food Database Deutschland bietet eine der größten deutschsprachigen Lebensmitteldatenbanken. Gerade für deutsche Marken und Eigenkreationen findest du dort oft passende Einträge. Für sauberes Tracken ist eine gute Datenbank die halbe Miete.',
            },
            {
                name: 'Yazio',
                type: 'Software',
                category: 'Apps',
                text: 'Yazio kombiniert Kalorienzählen mit einer übersichtlichen Oberfläche und vielen Community Funktionen. Barcode Scanner und Rezepte beschleunigen den Alltag. Die App eignet sich besonders für Einsteiger, die Struktur ohne Überforderung wollen.',
            },
            {
                name: 'MyFitnessPal',
                type: 'Software',
                category: 'Apps',
                text: 'MyFitnessPal hat international die größte Datenbank und funktioniert gut, wenn du oft englischsprachige Produkte trackst. Die kostenlose Version reicht für die meisten zum Start. Mit der Zeit lernt man, welche Einträge verlässlich sind und welche geschätzt werden müssen.',
            },
            {
                name: 'DailyTogether',
                type: 'Software',
                category: 'Tools',
                text: 'DailyTogether hilft Paaren, Familien und Haushalten, gemeinsam zu planen statt nebeneinander zu organisieren. Checklisten, Chat und Timer ersetzen kein Kalorientracking, ergänzen aber den Alltag, wenn mehrere Menschen einen Rhythmus brauchen.',
            },
            {
                name: 'eno.rocks',
                type: 'Software',
                category: 'Tools',
                text: 'Auf eno.rocks findest du meine Rechner, Begriffe und künftig mehr Ratgebercontent ohne Abo. Die Tools rechnen lokal im Browser und speichern keine Daten auf einem Server. Sie sind gedacht als Ergänzung zu Tracking Apps, nicht als Ersatz.',
            },
        ],
    },
    {
        id: 'top-hardware',
        format: 'toplist',
        title: 'Meine Top Hardware',
        lead: 'Die richtige Ausstattung spart Zeit und macht Tracking sowie Training zuverlässiger. Nicht alles ist Pflicht, aber diese Dinge haben sich bei mir langfristig gelohnt.',
        headerImage: 'headers/top-hardware.svg',
        items: [
            {
                name: 'Renpho Waage',
                type: 'Hardware',
                category: 'Tracking',
                text: 'Eine Körperanalysewaage schätzt neben Gewicht auch Körperfett und Muskelanteil über Bioimpedanz. Die absoluten Werte sind ungenau, der Trend über Wochen oft nützlich. Entscheidend bleibt, morgens unter gleichen Bedingungen zu messen und den Durchschnitt zu betrachten.',
            },
            {
                name: 'Kurzhanteln',
                type: 'Hardware',
                category: 'Training',
                text: 'Verstellbare Kurzhanteln ermöglichen Zuhause ein vollwertiges Krafttraining ohne Studio. Du kannst Gewicht stufenweise steigern und viele Grundübungen abdecken. Für Muskelaufbau und Muskelerhalt beim Abnehmen ist Widerstandstraining sehr empfehlenswert.',
            },
            {
                name: 'Hantelbank',
                type: 'Hardware',
                category: 'Training',
                text: 'Eine stabile Bank erweitert die Übungsauswahl für Brust, Schultern und Rücken deutlich. Schräglagen und gestütztes Rudern werden sicherer und effektiver. Ohne Bank bleibst du stärker bei Bodenübungen hängen.',
            },
            {
                name: 'Smartwatch',
                type: 'Hardware',
                category: 'Tracking',
                text: 'Eine Smartwatch zählt Schritte, Puls und manchmal Schlaf automatisch. Das hilft, Alltagsbewegung sichtbar zu machen, ohne alles manuell einzutragen. NEAT, also Bewegung außerhalb vom Sport, kann beim Kalorienverbrauch überraschend viel ausmachen.',
            },
            {
                name: 'Küchenwaage',
                type: 'Hardware',
                category: 'Küche',
                text: 'Wer tracken will, braucht eine digitale Küchenwaage. Öl, Nüsse, Pasta und Reis werden sonst fast immer unterschätzt. Mit der Zeit entwickelst du ein Gefühl, aber am Anfang ist Wiegen der schnellste Weg zu ehrlichen Zahlen.',
            },
            {
                name: 'Protein Shaker',
                type: 'Hardware',
                category: 'Küche',
                text: 'Ein guter Shaker mit Sieb verhindert Klumpen im Proteinpulver. Das klingt banal, macht den Unterschied aber im Alltag und unterwegs. Spül ihn direkt aus, sonst riecht er schnell unangenehm.',
            },
            {
                name: 'Heißluftfritteuse',
                type: 'Hardware',
                category: 'Küche',
                text: 'Heißluft braucht weniger Öl als klassische Fritteuse und macht Pommes, Gemüse oder TK Ware knusprig. Du sparst Kalorien aus Fett, ohne auf den Geschmack komplett zu verzichten. Portion und Temperatur trotzdem im Blick behalten.',
            },
        ],
    },
    {
        id: 'top-organisation',
        format: 'toplist',
        title: 'Meine Top Organisation',
        lead: 'Weniger Chaos in Küche und Vorrat bedeutet weniger impulsive Entscheidungen. Diese Hilfsmittel kosten wenig, sparen aber regelmäßig Zeit und Nerven.',
        headerImage: 'headers/top-organisation.svg',
        items: [
            {
                name: 'Etikettierer',
                type: 'Organisation',
                category: 'Küche',
                text: 'Beschriftete Behälter im Gefrierschrank verhindern, dass du Portionen vergisst oder wegwirfst. Du siehst sofort, was drin ist und wie alt es ist. Meal Prep funktioniert nur, wenn du es später auch wiederfindest.',
            },
            {
                name: 'Aufbewahrungsboxen',
                type: 'Organisation',
                category: 'Küche',
                text: 'Einheitliche Boxen stapeln sich gut und passen in Kühlschrank und Gefrierfach. Vorkochen lohnt sich erst, wenn Aufbewahrung hygienisch und übersichtlich ist. Glas oder hochwertiger Kunststoff hält länger und verzieht sich nicht so schnell.',
            },
            {
                name: 'Extra Messbecher',
                type: 'Organisation',
                category: 'Küche',
                text: 'Feste Messbecher für Haferflocken, Reis oder Milchpulver beschleunigen das Frühstück. Du musst nicht jeden Morgen neu abwiegen, bleibst aber bei gleichen Portionen. Das reduziert Entscheidungsmüdigkeit an stressigen Tagen.',
            },
        ],
    },
    {
        id: 'top-gewohnheiten',
        format: 'toplist',
        title: 'Meine Top Gewohnheiten',
        lead: 'Tools helfen, aber Verhalten trägt langfristig. Diese Gewohnheiten haben bei mir den größten Effekt auf Körpergewicht, Energie und Konstanz gehabt.',
        headerImage: 'headers/top-gewohnheiten.svg',
        items: [
            {
                name: 'Kalorien zählen',
                type: 'Gewohnheit',
                category: 'Tracking',
                text: 'Bewusstes Erfassen von Essen schafft ehrliches Feedback, wie viel du wirklich isst. Am Anfang ist es mühsam, nach einigen Wochen erkennst du Muster und Portionsgrößen. Du musst nicht ewig jede Mahlzeit loggen, aber eine Phase mit Tracking lohnt sich fast immer.',
            },
            {
                name: 'Protein hoch halten',
                type: 'Gewohnheit',
                category: 'Ernährung',
                text: 'Ausreichend Protein unterstützt Muskelerhalt im Defizit und erhöht die Sättigung pro Mahlzeit. Viele landen ohne Plan bei 60 bis 80 Gramm, obwohl 1,6 bis 2 Gramm pro Kilogramm Körpergewicht oft sinnvoll sind. Protein priorisieren ist einfacher als jede Diätform perfekt umzusetzen.',
            },
            {
                name: 'Täglich wiegen',
                type: 'Gewohnheit',
                category: 'Tracking',
                text: 'Das Körpergewicht schwankt täglich durch Wasser, Salz und Verdauung. Trotzdem liefert tägliches Wiegen genug Datenpunkte für einen Wochentrend. Einzelne Tage ignorieren, den Durchschnitt lesen, das verhindert Frust.',
            },
            {
                name: 'Geduld',
                type: 'Gewohnheit',
                category: 'Mindset',
                text: 'Fettabbau braucht Wochen und Monate, nicht Tage. Realistische Erwartungen schützen vor dem Gefühl, es funktioniere nicht, obwohl der Trend stimmt. Wer zu aggressiv startet, riskiert Heißhunger und den Jo Jo Effekt.',
            },
            {
                name: 'Intermittierendes Fasten',
                type: 'Gewohnheit',
                category: 'Ernährung',
                text: 'Ein festes Essensfenster kann helfen, weniger zu essen, ohne jedes Lebensmittel zu verbieten. Es wirkt vor allem, weil die Gesamtkalorien sinken, nicht wegen magischer Stoffwechsel Effekte. Wenn du morgens hungrig bist oder abends trainierst, passt das Modell nicht für jeden.',
            },
        ],
    },
];
